application: asylum-inmate-hrd
version: 2
runtime: python27
api_version: 1
threadsafe: true


libraries:
- name: jinja2
  version: latest


builtins:
- deferred: on


handlers:
- url: /
  script: home.app

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

# calennar
- url: /calennar/update
  script: calennar.app
  login: admin

- url: /calennar/.*
  script: calennar.app

# embed tweet
- url: /tweet
  script: tweet.app

- url: /tweet/setup
  script: tweet.app
  login: admin

- url: /tweet/.*
  script: tweet.app
