application: asylum-inmate
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: home.py

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

# calennar
- url: /calennar/update
  script: calennar.py
  login: admin

- url: /calennar/.*
  script: calennar.py

# blackbird
- url: /tweet
  script: tweet.py

- url: /tweet/setup
  script: tweet.py
  login: admin

- url: /tweet/.*
  script: tweet.py

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin
