application: asylum-inmate
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: home.py

- url: /calennar/update
  script: calennar.py
  login: admin

- url: /calennar/.*
  script: calennar.py

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin
